### PR TITLE
Add UI scaling support

### PR DESCRIPTION
**Pull request by BillyDM**

### CODE REVIEW

**Comment by wrl** [comment]
Did you test this?

**Comment by BillyDM** [comment]
Yes, I have tested it.

**Comment by wrl** [comment]
The issue here is that some hosts ask for the window size before they open the editor, and I think that this PR breaks that case.

**Comment by BillyDM** [comment]
Oh, I see. So should we keep the `ui_size()` for the PluginUI trait, and then resize the window later?

**Comment by wrl** [comment]
This PR introduces a bunch of new code and types but doesn't actually fix the problem.

The problem is that we need to know the scaling factor in `ui_size()` before returning to the host. There are two places this can come from:

1. In some hosts, we can use a VST extension (which exists both for VST2 and VST3) to receive notifications from the host about the scaling factor. This API is defined in the [Presonus VST extensions](https://presonussoftware.com/en_US/developer) (bottom of the page).
1. We can check in with the window system. On macOS, the scaling ratio will always be `1.0` (even on retina, because the window size is handled at a lower level). On Windows, there's a complex bit of footwork we have to do in order to figure out where the scaling ratio is defined (with different APIs depending on the Windows version). On Linux, we already have the code implemented for querying the DPI from the X server, but we don't have this exposed as a public API.

So, I think there's a two-part change that has to happen here:

1. We need to pass a `host_ui_scale: Option<f32>` to `ui_size()` which we get from the host using the above VST extension.
1. We need to expose an API from baseview that makes a "best effort" at getting the DPI/scaling as a fallback if the host has not informed us of its own DPI/scaling.

I'm not comfortable with the additional code that this PR adds, especially considering that baseplug doesn't actually need to know about the "logical" window size at all. When the host asks for the window size, it's only asking for the *physical* size (i.e. the size in window-server-space). It's well within reason that a plugin with flexible UI scaling (for example, the Valhalla or Audio Damage plugins, which let the user rescale the plugin by dragging) would *ignore* the platform UI scaling if it so chooses.

For those reasons, I'm going to close this PR, but I hope this reply has provided some direction about future steps in baseplug. I'll take a look at the baseview PR next.

**Comment by BillyDM** [comment]
Alright, makes sense. I'll look into the VST extensions more and see what I can do.

**Pull request closed without merging**
